### ISSUE TITLE
Beacons graph not entirely correct?

### ISSUE THREAD

**Issue by spasaintk** [synfinatic/helium-analysis#47]
Hi,

First off; Thanks for adding the enhancement requests!

For the beacon graphs: There are days where no beacons are being sent, this is however not reflected in the total beacons graphs. For example the graph below hasn't sent any beacons for the past few days. Currently the tool either doesn't generate anything for these days as visible in the first graph, or sometimes when a day has no data, it just keeps the line at 18 as visible at the second graph. Is this intended behavior? It feels like it should not show any data on those days, but keep advancing the graph (it shows this behavior for the peer witness graphs).

I have one more enhancement request (for now) :) :
- Ability to supply a list of miner addresses 

![image](https://user-images.githubusercontent.com/6660834/149747197-c1729671-6194-44ba-9d69-3c847b3b2293.png)

![image](https://user-images.githubusercontent.com/6660834/149747615-aa1be7ce-e19d-4cda-b4e7-9adb114c4aa6.png)

**Comment by synfinatic** [comment]
The up and to the right, followed by a flat line is intended because these graphs show the total over time.  So when the graph is going up and to the right, there are beacons.  The graph represents the total (`previous + now`).  So when there is a flat line, it shows there aren't any new beacons so the `previous + now = previous`.

**Comment by spasaintk** [comment]
Hi,

Thanks for your answer. 

It makes this graph a bit confusing if this is the intended behaviour. The screenshot below is the data for the top graph (melted sangria ape). Ignore the new result for today as that wasn't included in the graph posted earlier.
If you look at the data below, is the graph above from the tool the intended behaviour?(I guess its behaving like the graph on the left)

Cheers,

![image](https://user-images.githubusercontent.com/6660834/149816036-6bee2018-98ca-46cb-b618-a73975e12d74.png)

**Comment by synfinatic** [comment]
I get what you're trying to say... but I also would say "if there is another tool which does A, then I don't need to do A again"

That and honestly, I'm not really maintaining this project beyond "keeping the lights on".  This was much more interesting to me when rewards were more meaningful, but the number of hotspots has grown to the point it's just not really worth my time to make more than simple changes.

So, if the other tool generates graphs that make more sense to you, I'd suggest you use that tool. :)

**Comment by spasaintk** [comment]
Hi,

Sure thing :) If it's not being developed then it's all good! 
I realize there's the other tools, but I like to run things off my own server, and your tool provides pretty much all I wanted from the data.

Thanks anyway!

Cheers,
